### ISSUE TITLE
Should not trigger on byte strings

### ISSUE THREAD

**Issue by ghost** [atugushev/flake8-printf-formatting#9]
(Partially copied from MichaelKim0407/flake8-use-fstring#22, as this plugin also suffers from the same issue.)

The following code triggers a MOD001 error:

```py
a = 42
b"y=%d" % a
```
However, using an f-string with a byte string is a syntax error:
```
>>> bf"y={a}"
  File "<stdin>", line 1
    bf"y={a}"
      ^^^^^^^
SyntaxError: invalid syntax
```

And `.format()` is not an option either:
```
>>> b"y={}".format(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bytes' object has no attribute 'format'
```

The only other option is `.join()` or string concatenation, which are less elegant IMO.

(I *could* also do `"y={}".format(a).encode("utf-8")`, but that doesn't always work right if there are byte literals in the string.)

**Comment by atugushev** [comment]
Thanks for the report! Indeed bytes should be excluded.
